### ISSUE TITLE
Error with PhpUnit

### ISSUE THREAD

**Issue by iriartmaxim** [farindra/lumen-jwtauth#3]
PHP Fatal error:  Uncaught Error: Class 'TestCase' not found in /srv/laravel/lumen-jwtauth/tests/EndpointTests.php:5
Stack trace:
#0 /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/Util/FileLoader.php(65): include_once()
#1 /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load()
#2 /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php(43): PHPUnit\Util\FileLoader::checkAndLoad()
#3 /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(146): PHPUnit\Runner\StandardTestSuiteLoader->load()
#4 /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php(112): PHPUnit\Runner\BaseTestRunner->loadSuiteClass()
#5 /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/TextUI/Command.php(120): PHPUnit\Runner\BaseTestRunner->getTest()
#6 /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run()
#7 phpvfscomposer:///srv/laravel/lumen-jwtauth/vendor/php in /srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/src/TextUI/Command.php on line 98

I have this problem and I don't know what can be. 

Can you help me, please? @farindra

**Comment by iriartmaxim** [comment]
I can fix the first problem.

Now I have a new problem 

EE                                                                 3 / 3 (100%)

Time: 00:00.062, Memory: 20.00 MB

There were 3 errors:

1) EndpointTest::test_unknown_path_should_404
ErrorException: Undefined property: Illuminate\Http\JsonResponse::$response

/srv/laravel/lumen-jwtauth/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:1528
/srv/laravel/lumen-jwtauth/tests/EndpointTest.php:21
phpvfscomposer:///srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/phpunit:97

2) EndpointTest::test_get_version
Symfony\Component\Routing\Exception\RouteNotFoundException: Route [v1.version] not defined.

/srv/laravel/lumen-jwtauth/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:444
/srv/laravel/lumen-jwtauth/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:739
/srv/laravel/lumen-jwtauth/tests/EndpointTest.php:33
phpvfscomposer:///srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/phpunit:97

3) EndpointTest::test_ping_should_return_pong
Symfony\Component\Routing\Exception\RouteNotFoundException: Route [v1.ping] not defined.

/srv/laravel/lumen-jwtauth/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:444
/srv/laravel/lumen-jwtauth/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:739
/srv/laravel/lumen-jwtauth/tests/EndpointTest.php:48
phpvfscomposer:///srv/laravel/lumen-jwtauth/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 3, Assertions: 0, Errors: 3.

I finished the step when i must make the routes

**Comment by farindra** [comment]
How you fix the first problem?

**Comment by iriartmaxim** [comment]
The first problem reason is: add "use Tests/TestCase" in EndpointTest.php

**Comment by iriartmaxim** [comment]
Hi, i resolv the second problem.

**Comment by iriartmaxim** [comment]
This is a last issue with this.

![imagen](https://user-images.githubusercontent.com/97992995/170562276-6a9b8f77-45a4-4e5d-8f71-df2fd405b2c4.png)
I finished the lab but this it's holding me.
